### ISSUE TITLE
Add a "cleanup" playbook

### ISSUE THREAD

**Issue by jmaupetit** [openfun/arnold#135]
## Purpose

When a deployment fails, some objects created during that deployment are left as is and we have no cleanup tool to delete them.

## Proposal

We need to write a cleanup playbook that removes every object labelled with a `deployment_stamp` that is not associated to a stack attached to a route (previous, current or next).

**Comment by sampaccoud** [comment]
@jmaupetit We could use a cronjob (an OpenShift job of type cron) with a schedule to run and clean orphan objects.
