### ISSUE TITLE
Automate generation of vault files for each app when adding a customer in a given environment

### ISSUE THREAD

**Issue by sampaccoud** [openfun/arnold#154]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
The vault files should be generated automatically when adding a customer

**Describe the solution you'd like**
Add a jinja template in each app to describe how the vault file looks. 
Passwords fields should specify random strings with appropriate format for each secret.

**Describe alternatives you've considered**
We could continue doing it manually.

**Comment by jmaupetit** [comment]
This feature should be part of #14, but can be implemented separately as a first step of the "add new customer" roadmap.
