### ISSUE TITLE
🐛(forum) URL encode MONGOHQ_URL components

### ISSUE THREAD

**Issue by jmaupetit** [openfun/arnold#174]
## Purpose

Some parts of the `MONGOHQ_URL` variable may break MongoDB access if they contain special characters (_e.g._ `:` or `/`).

## Proposal

- [ ] apply the [`urlencode` Jinja filter](http://jinja.pocoo.org/docs/2.10/templates/#urlencode) to the user password

**Comment by sampaccoud** [comment]
@jmaupetit Isn't it better to do it in `openedx-docker` so that:
- we solve the problem a its root, incl. for people who will use our Docker image but not Arnold,
- we avoid having 2 versions of the password in our templates with the confusion it creates?

**Comment by jmaupetit** [comment]
It is related to the forum app, not edxapp.
