### ISSUE TITLE
htpasswd are modified when deploying a fully defined project

### ISSUE THREAD

**Issue by sampaccoud** [openfun/arnold#187]
## Bug Report

**Expected behavior/code**
on a project for which the htpasswd secrets have already been generated and committed, deploying the project to OpenShift should not modify the htpasswd files.

**Actual Behavior**
Running the "init" playbook regenerates a set of htpasswd files:
```bash
modified:   group_vars/customer/foo/production/secrets/htpasswd/edxapp/htpasswd
modified:   group_vars/customer/foo/production/secrets/htpasswd/forum/htpasswd
modified:   group_vars/customer/foo/production/secrets/htpasswd/mailcatcher/htpasswd
modified:   group_vars/customer/foo/production/secrets/htpasswd/redis/htpasswd
```

**Steps to Reproduce**
1. create a customer with all its secrets and commit all the files
2. run bin/init
3. see the modified files

**Environment**
- Arnold version:
- Platform:

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jmaupetit** [comment]
That's an odd behavior. As mentioned in the [`htpassword` module's documentation](https://docs.ansible.com/ansible/latest/modules/htpasswd_module.html), we should define the `state=present` property to only create them if they do not exist. I thought it was the default.
