### ISSUE TITLE
Test switch playbook in the CI

### ISSUE THREAD

**Issue by lunika** [openfun/arnold#190]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**

`switch` is a critical playbook, it is the cornerstone in the blue/green strategy implemented in arnold. Today in each PR we have no idea if there are side effects on this playbook if we don't test it manually.

**Describe the solution you'd like**

After each bootstrap succeeded we should run a switch and then test the service on the `current` route.

**Comment by jmaupetit** [comment]
> After each bootstrap succeeded we should run a switch and then test the service on the current route.

You mean in the CI? I vote: yes!

**Comment by lunika** [comment]
> You mean in the CI? I vote: yes!

Exactly, this is why `Circleci` is mentionned in the title
