### ISSUE TITLE
Do not create prefixed routes for non-blue-green apps

### ISSUE THREAD

**Issue by jmaupetit** [openfun/arnold#191]
## Purpose

For each route, the `init_project` playbook creates 3 prefixed routes (previous/current/next) even if only the "current" route will be used. This can be improved.

## Proposal

- [ ] Conditionally create prefixed routes if an app is blue-green compatible

**Comment by lunika** [comment]
This is already the case. For non blue-green compatible application only one route is created, not 3. The only thing missing is removing the prefix in the mailcatcher route which is by default next.

**Comment by jmaupetit** [comment]
My bad, yes. This has already been implemented. I should sleep more. Sorry for the noise.
