### ISSUE TITLE
Add playbook to update routes on an existing project

### ISSUE THREAD

**Issue by sampaccoud** [openfun/arnold#208]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
For a project that is already deployed in OpenShift, it may happen that:
- some routes have been altered or worse deleted,
- some improvements are made to Arnold after the project was deployed which modify the routes.

The routes creation is done in the `init` playbook so it can't be updated after the project has been created.

**Describe the solution you'd like**
Add a playbook to update a project's routes. It could be called `routes`.
It could be included in `init` and also be run separately.

**Discovery, Documentation, Adoption, Migration Strategy**
Update the README and documentation to describe this new playbook.

**Comment by jmaupetit** [comment]
Fixed in #231
