### ISSUE TITLE
Declare reclaim policies to “Retain”  for all PVC in production environment

### ISSUE THREAD

**Issue by sampaccoud** [openfun/arnold#223]
## Bug Report

**Expected behavior/code**
When deleting a PVC (by mistake?) on a production installation, we don't want the data to be automatically deleted and lost.

**Actual Behavior**
By default Kubernetes assigns a reclaim policy of “Delete” to all PVC as explained here:
https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/#why-change-reclaim-policy-of-a-persistentvolume

**Possible Solution**
I think we should declare all our PVC with a reclaim policy of "Retain" in production.

**Comment by lunika** [comment]
This should be configurable and by default we chan choose `Retain` ?

**Comment by jmaupetit** [comment]
I'll propose something to fix this.

**Comment by jmaupetit** [comment]
This must be a globally configurable policy and not per app/volume right?

**Comment by jmaupetit** [comment]
This policy cannot be stated in the PVC but in the storage class that is configured at the cluster level.
