### ISSUE TITLE
Create a Docker image of the master branch

### ISSUE THREAD

**Issue by lunika** [openfun/arnold#243]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**

If we want to use Arnold in other project, like Matsuo, we always to respect a given process:

- Work in arnold.
- Create a PR.
- Release a new version of Arnold.
- Use this new version in Matsuo

Doing this we release often Arnold (this is not really a problem) and we always have to wait a release to start working/testing in matsuo.

The idea will be to not wait an Arnold release to start working in Matsuo.

**Describe the solution you'd like**

We can add a new circle-ci task dedicated to tag and push a new docker image every time a modification is made in master branch. Basically every time a PR is merged a new image is created and tag with `master` name.

**Do you want to work on it through a Pull Request?**

Yes I can.

**Comment by jmaupetit** [comment]
Fixed in #245
