### ISSUE TITLE
Allow deactivating signed URLs in Marsha

### ISSUE THREAD

**Issue by sampaccoud** [openfun/arnold#277]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
PR https://github.com/openfun/arnold/pull/276 has removed the possibility to deactivate CloudFront signed URLs in Marsha although there is the possibility to do so in the application.

**Describe the solution you'd like**
Once this PR https://github.com/openfun/marsha/issues/263 is done in Marsha, we should consider adding back the feature.

**Comment by jmaupetit** [comment]
I've finally rolled back my changes in #276.
