### ISSUE TITLE
Enforce OpenShift host for a given environment

### ISSUE THREAD

**Issue by sampaccoud** [openfun/arnold#28]
## Purpose

The OpenShift host is set in the env.d environment files. This means that we could end-up mistakenly deploying a "feature" environment to the production host for example.

## Proposal

Set the `K8S_AUTH_HOST` in group_vars and jinja templates instead of `env.d` files.

- [ ] Add a variable `openshift_host` in group_vars:
        * in main.yml set it to the value of the `K8S_AUTH_HOST` environment variable
        * in each environment files, set it to their specific value (minishift, openshift dev or openshift prod)
- [ ] Set a "metadata" in the `create_objects` playbook to enforce the `host` for all tasks in the playbook as specified in `openshift_raw` documentation https://docs.ansible.com/ansible/2.5/modules/openshift_raw_module.html

**Comment by jmaupetit** [comment]
Closing this as this is no longer the case as the targeted host is set by the console you logged in to _via_ `oc login`.
