### ISSUE TITLE
Add create_users job

### ISSUE THREAD

**Issue by jmaupetit** [openfun/arnold#3]
## Purpose

We need to automate the user account creation for every Django service/flavor/customer Arnold will deploy.

## Proposal

Add a `create_users` job, that will actually create a superuser and other profiles using django management commands and vaulted credentials.

**Comment by sampaccoud** [comment]
@jmaupetit I think for Open edX we need more profiles: student, teacher, staff, superuser, etc.

**Comment by jmaupetit** [comment]
True. I've updated the issue title and description.

**Comment by jmaupetit** [comment]
For `edxapp`, we've finally decided to create open edx standard demo users in the `import_demo_course.yml.j2` template.

**Comment by jmaupetit** [comment]
It needs to be a separated job for Richie.

**Comment by sampaccoud** [comment]
Fixed in https://github.com/openfun/arnold/commit/fdadc6a7b2831ea163f078199ad564c6244b7f0a
