### ISSUE TITLE
edxapp: add attestation volume

### ISSUE THREAD

**Issue by jmaupetit** [openfun/arnold#392]
## Purpose

Fun-mooc's `edxapp` instance requires a volume to persist attestations.

## Proposal

- [ ] add a new `attestation` volume
- [ ] attach the `attestation` volume to DCs

**Comment by sampaccoud** [comment]
Since this is specific to fun-mooc, we did not want to adapt Arnold to it and solved the problem by relocating certificates to the media directory. See PR https://github.com/openfun/openedx-docker/pull/171
