### ISSUE TITLE
Allow customizing the list of configmaps per customers and environments

### ISSUE THREAD

**Issue by sampaccoud** [openfun/arnold#40]
## purpose

The playbook that creates configmaps automatically find them in the `templates/configmap` directory and pushes them all to OpenShift. We want to be able to define which configmaps are created for each customer or env_type. 

For example, the "edxapp-fixtures" configmap should only be created for the `development` or `feature` environments.

## Proposal

Apply the same mechanism as for OpenShift objects to configmaps:

- [ ] List configmaps in an Ansible variable called `openshift_configmaps` that can be overridden by customer/env_type,
- [ ] Stop autodiscovering configmaps in the playbook but use the `openshift_configmaps` variable.

**Comment by jmaupetit** [comment]
Closing this as this feature already has already been implemented.
