### ISSUE TITLE
Make projects customizable

### ISSUE THREAD

**Issue by sampaccoud** [openfun/arnold#44]
## Purpose

We project to be customizable so that anyone can use Anrold as a tool to build their own project.

## Proposal

Add a new directory with the following structure:

```
├── examples
│   └── hello
│       └── templates
│           └── ...
│       └── group_vars
│           └── ...
│   └── openedx
│       └── templates
│           └── ...
│       └── group_vars
│           └── ...
│   └── richie
│       └── templates
│           └── ...
│       └── group_vars
│           └── ...

```

In order to deploy one of these projects, the scripts should run docker mounting the `templates` and `group_vars` directories in the *arnold directory.

- [ ] move the existing specific configuration to a private repository
- [ ] delete the `files` directory as it won't be used for the moment
- [ ] add the examples directory and split the current templates/vars into 3 projects: hello, openedx, richie
- [ ] modify the `_docker_run` bash command to take the project name as an argument.

**Comment by jmaupetit** [comment]
This has been implemented in #62
