### ISSUE TITLE
Unable to put a valid JSON file to a ConfigMap (from a Jinja2 template)

### ISSUE THREAD

**Issue by madmatah** [openfun/arnold#450]
## Bug Report

**Expected behavior/code**

I would like to generate a JSON file from a Jinja2 template, in order to put it in a ConfigMap.

**Actual Behavior**

The deploy playbook fail with the following error in the task _Create the config maps in OpenShift_ : 

```
failed: [local] (item={'key': 'app', 'value': {'test.json': {'stamp': 'd-200128-08h49m48s', 'project': 'development-eugene'}}}) => {"ansible_loop_var": "item", "changed": false, "error": 400, "item": {"key": "app", "value": {"test.json": {"project": "development-eugene", "stamp": "d-200128-08h49m48s"}}}, "msg": "Failed to create object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"ConfigMap in version \\\\\"v1\\\\\" cannot be handled as a ConfigMap: [pos 242]: json: expect char \\'\\\\\"\\' but got char \\'{\\'\",\"reason\":\"BadRequest\",\"code\":400}\\n'", "reason": "Bad Request", "status": 400}
```

**Steps to Reproduce**
1. Create a file `apps/hello/templates/services/app/configs/test.json.j2` with the following content : 
```json
{
  "stamp": "{{ deployment_stamp }}",
  "project": "{{ project_name }}"
}
```
2. Deploy the hello app
3. And then the bug happens!

**Environment**
- Arnold version: 4.7.0 on `master`
- Platform: linux / oc 3.11

**Possible Solution**

I tried to patch the _Format configMaps_ task in `tasks/create_app_config.yml` with an explicit cast to string for every rendered templates : 

```
{%- set content = lookup('template', cm_path)|string -%}
```

The `deploy` playbook is not failing anymore, but if I inspect the content of the generated ConfigMap, I can see that my JSON content has been altered (double quotes are converted to single quotes) and is invalid : 

```
$> oc describe cm hello-app-d-200128-09h01m37s
Name:         hello-app-d-200128-09h01m37s
Namespace:    development-eugene
Labels:       app=hello
              deployment_stamp=d-200128-09h01m37s
              service=app
Annotations:  <none>

Data
====
test.json:
----
{'stamp': 'd-200128-09h01m37s', 'project': 'development-eugene'}
Events:  <none>
```

**Additional context/Screenshots**

More informations [here](https://github.com/ansible/ansible/issues/44897#issuecomment-417340295)

**Comment by jmaupetit** [comment]
Have you tried the `from_json` filter? Maybe we should handle this special case explicitly.

https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#filters-for-formatting-data

**Comment by madmatah** [comment]
> Have you tried the `from_json` filter? Maybe we should handle this special case explicitly.
> 
> https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#filters-for-formatting-data

Nope, I didn't try because I would like to avoid making a special case for 1 file type.
But if we have no other options, I will try :smile: 

I think I just found a solution with the `convert_data=False` argument in the [lookup](https://docs.ansible.com/ansible/latest/plugins/lookup/template.html) filter.
I'll make a Pull Request.
