### ISSUE TITLE
Switch routes for blue green deployments

### ISSUE THREAD

**Issue by sampaccoud** [openfun/arnold#47]
## Purpose

Currently, our deployments create new complete stacks including routes to access each stack.
In a functional architecture, we need to manage routes differently to allow uninterrupted service when making a new deployment.

## Proposal

Stop creating routes together with the stack of svc/dc/ep.

Create only 3 routes for each service. The following hosts are examples for the lms:

- previous: "**previous**.lms.{{ project_name }}.{{ domain_name }}"
- current: "lms.{{ project_name }}.{{ domain_name }}"
- next: "**next**.lms.{{ project_name }}.{{ domain_name }}"

Each time we make a new deployment, the following actions are taken:

1) create the new stack,
2) create/update the next route:
    - if the "next" route pre-existed, update it to point to the new stack. Delete the stack that was previously pointed by the "next" route, making sure that it is not pointed by the "current" route (it is normally not possible but could happen if something went wrong in a route switch... so let's check that explicitly before deleting it),
    - if the "next" route did not exist, create it and point it to the new stack.

Each time we confirm a deployment by triggering a route switch, the following actions are taken:

1) point the "current" route to the stack that was pointed by the "next" route,
2) point the "previous" route to the stack that was pointed by the "current" route just before we changed it in 1)
3) delete the stack that was pointed by the "previous" route just before we changed it in 2) 
4) delete the next route

**Comment by jmaupetit** [comment]
This is fixed since 7ee5e601acde595743045d40628415d0f0c90a94
