### ISSUE TITLE
Fix requests dependency warning for urllib3

### ISSUE THREAD

**Issue by cchaudier** [openfun/arnold#65]
## Purpose

The following warning message appeared recently:

```
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```

## Proposal

It should be fixed!

**Comment by jmaupetit** [comment]
I think it will be solved when switching to python 3.6. So basically it's related to #78

**Comment by jmaupetit** [comment]
I think this has already been fixed. Can you confirm @lunika?

**Comment by lunika** [comment]
I never saw this warning, maybe I don't use the good verbosity level to see it.

**Comment by jmaupetit** [comment]
No you would have seen it already. I'll close this issue.

**Comment by Aeres-u99** [comment]
```
/usr/local/lib/python3.6/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.24.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```

is it really fixed?

**Comment by jmaupetit** [comment]
@Aeres-u99 which release of Arnold are you running?

**Comment by Aeres-u99** [comment]
Oh no ;-; I am really sorry I didnt really checked the repository and filed the issue thinking it was the one for requests module. My real bad

**Comment by Aeres-u99** [comment]
I would still appreciate the methodology used to fix the issue for arnold, like was it a try catch or some sort of upgrade? 
(Deepest apology for inconvenience)
