### ISSUE TITLE
[CLI] The `vaults` command is not working as expected

### ISSUE THREAD

**Issue by madmatah** [openfun/arnold#651]
## Bug Report

**Expected behavior/code**

The `vaults` command proposed by Arnold CLI is supposed to _perform global actions for all namespace vaults_.

For example, we should be able to decrypt all vaults for the application `edxapp` in all namespaces with the following command :

`$> bin/arnold vaults -a edxapp decrypt`

**Actual Behavior**

The command fails with the following error : 

`ERROR    You need to set both the ARNOLD_CUSTOMER and ARNOLD_ENVIRONMENT environment variables (see usage).`

**Steps to Reproduce**
1. `bin/arnold vaults -a edxapp decrypt`

**Environment**
- Arnold version: `master` branch
- Platform: linux

**Comment by jmaupetit** [comment]
I think we should update the command description to clarify that it targets all vaults from the current namespace and not vaults from all namespaces. WDYT?

**Comment by madmatah** [comment]
Hmm yes indeed :+1: 
I didn't understand it this way, I had another use case in mind.
