### ISSUE TITLE
Kubernetes Deployment:Richie 

### ISSUE THREAD

**Issue by aarajbhattarai** [openfun/arnold#664]
Can anybody please provide instructions for setting Kubernetes cluster in migration-to-k8s branch?

Thank you

**Comment by iliemihai** [comment]
@jmaupetit 
I had managed to run arnold using Kubernetes cluster in migration-to-k8s branch by using the output from the tests in circleci from https://app.circleci.com/pipelines/github/openfun/arnold. In fact I could not run the old arnold with openshift, so I run it with Kubernetes, it works like a charm :D

For installing Kubernetes you can go for example in test-k3d-cluster-registry  and check the commands. After that you can install Richie, Marsha in arnold and check them in browser.

I have one question though. How can we use arnold to run an actual MOOC like https://www.fun-mooc.fr ? 
Thank you

**Comment by aarajbhattarai** [comment]
There is tray package for funmooc.
https://github.com/openfun/richie-site-factory/tree/add-arnold-package

**Comment by aarajbhattarai** [comment]
Hi @iliemihai ,
Can you please help me out ? I have installed the kubectl and k3d using brew and then built the Arnold images.
**COMMANDS**
make build && make build-dev
mkdir -p /tmp/docker/images
docker save -o /tmp/docker/images/arnold.tar arnold
docker load < /tmp/docker/images/arnold.tar
MINIMUM_AVAILABLE_RWX_VOLUME=15 K3D_BIND_HOST_PORT_HTTP=80 K3D_BIND_HOST_PORT_HTTPS=443 make cluster

**ERROR**
readlink: illegal option -- f
usage: readlink [-n] [file ...]
WARN[0000] No node filter specified                     
INFO[0000] Prep: Network                                
INFO[0000] Re-using existing network 'k3d-arnold' (6089740928d5f67dd19c5a70353c07bd28988c963b94bb73ecbadfc866ad60ba) 
INFO[0000] Created volume 'k3d-arnold-images'           
INFO[0001] Creating node 'k3d-arnold-server-0'          
ERRO[0001] Failed to create container 'k3d-arnold-server-0' 
ERRO[0001] Failed to create node 'k3d-arnold-server-0'  
ERRO[0001] Failed to create node                        
ERRO[0001] Failed Cluster Creation: Error response from daemon: create ./k3d-storage: "./k3d-storage" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path 
ERRO[0001] Failed to create cluster >>> Rolling Back    
INFO[0001] Deleting cluster 'arnold'                    
ERRO[0001] No nodes found for given cluster             
FATA[0001] Cluster creation FAILED, also FAILED to rollback changes! 
make: *** [cluster] Error 1

Thank you!
