### ISSUE TITLE
Cluster Volume Error

### ISSUE THREAD

**Issue by aarajbhattarai** [openfun/arnold#675]
## Bug Report

**Expected behavior/code**
Creation of cluster

**Actual Behavior**
make cluster
readlink: illegal option -- f
usage: readlink [-n] [file ...]
WARN[0000] No node filter specified                     
INFO[0000] Prep: Network                                
INFO[0000] Re-using existing network 'k3d-arnold' (b738e8de245559a843541bd802166913bb15b879de38e02f496d9fbea39b75ca) 
INFO[0000] Created volume 'k3d-arnold-images'           
INFO[0001] Creating node 'k3d-arnold-server-0'          
ERRO[0001] Failed to create container 'k3d-arnold-server-0' 
ERRO[0001] Failed to create node 'k3d-arnold-server-0'  
ERRO[0001] Failed to create node                        
ERRO[0001] Failed Cluster Creation: Error response from daemon: create ./k3d-storage: "./k3d-storage" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path 
ERRO[0001] Failed to create cluster >>> Rolling Back    
INFO[0001] Deleting cluster 'arnold'                    
ERRO[0001] No nodes found for given cluster             
FATA[0001] Cluster creation FAILED, also FAILED to rollback changes! 
make: *** [cluster] Error 1

**Steps to Reproduce**
1. Do this...
2. Then this...
3. And then the bug happens!

**Environment**
- Arnold version: 6.0.0
- Platform: MacOs BigSur Version 11.4

**Possible Solution**
Using $pwd to provide the absolute path

**Additional context/Screenshots**
sudo sysctl -w vm/max_map_count=262144
**OUTPUT**
sysctl: unknown oid 'vm/max_map_count'

**Comment by madmatah** [comment]
Thanks for your feedback @aarajbhattarai

arnold CLI uses the `-f` option of `readlink` that is unsupported by the MacOS version of `readlink`.
We should fix it to use a POSIX compliant alternative.

In the meantime, I can suggest you to install the coreutils to have a version of `readlink` that supports the `-f` option:

```shell
brew install coreutils --with-default-names
```


About `sysctl` command to tune `vm/max_map_count` for Elasticsearch, you might try [this solution on Mac](https://stackoverflow.com/a/41251595)

**Comment by aarajbhattarai** [comment]
Thank you so much @madmatah 
File: bin/init-cluster
Objective: Generate an unique identifier for the PV
`PV_ID=$(uuidgen)`
On Linux this command returns a lowercase string of a UUID.
But on Mac OS X it returning an uppercase string of a UUID.
The solution for MacOs would be
`PV_ID=$(uuidgen | tr "[:upper:]" "[:lower:]") `
