### ISSUE TITLE
Add health checks to all our applications

### ISSUE THREAD

**Issue by sampaccoud** [openfun/arnold#69]
## Purpose

We need to configure health checks.

## Proposal

I propose following Mozilla's Docker flow:

- first consider adding https://github.com/mozilla-services/python-dockerflow to each of our projects,
- configure healthchecks in OpenShift to monitor the /__heartbeat__ and /__lbheartbeat__ endpoints.

**Comment by jmaupetit** [comment]
Never heard of `python-dockerflow` :+1:

**Comment by cchaudier** [comment]
I think https://github.com/mozilla-services/Dockerflow is a better alternative with /__heartbeat__ and /__lbheartbeat__
