### ISSUE TITLE
Group apps by their name in OpenShift's console

### ISSUE THREAD

**Issue by cchaudier** [openfun/arnold#71]
## Purpose

OpenShift can group services belonging to the same app in the console. While the monitoring a project (customer + environment), we want to see all pods of one app, this can be achieved thanks to the app name filter.

## Proposal

- [ ] use `{{ apps.name }}` in templates to group all services under the same app in OpenShift

**Comment by jmaupetit** [comment]
This is now fixed since b4ef7fecf575759d066588d20c2cdd5f446ea073
