### ISSUE TITLE
Error "Invalid vault password was provided from script" during deployment

### ISSUE THREAD

**Issue by moticanvm** [openfun/arnold#716]
### Bug Report

**Expected behavior/code**
A new application would be deployed and a pod would be created on Kubernetes

**Actual Behavior**
when execute "bin/arnold -c hd-inc -e development -a hello create_app_vaults" I got this error as return response:

Command: create_app_vaults

Parameters:
  K8S_DOMAIN  : 10.128.15.236
  application : hello
  customer    : hd-inc
  environment : development
  gpg enabled : 0
  dev mode    : 0
  log level   : info
  CLI release : 6.5.2
  image       : arnold:6.5.2
  extra volume: 

WARNING  We strongly recommend to activate the GPG mode to secure your vault passwords
**[WARNING]: Error in vault password file loading (default): Invalid vault password was provided from
script (/usr/local/bin/vault-password)
ERROR! Invalid vault password was provided from script (/usr/local/bin/vault-password)**
<>

**Steps to Reproduce**
Do the steps described on `Quick start for Arnold's developers`

**Environment**
Using an google instance with Ubuntu 18.04
kubectl 1.23.1
k3d version 4.4.8
docker 20.10.12

Tried on arnold version 5.24.0, 5.25.0, 6.5.2 and 6.8.1 - same result for all

**Comment by jmaupetit** [comment]
Hi @moticanvm :wave: 

Looks like the documentation is unclear on this point, thank you for your feedback.

For testing purpose, if you don't need to use a `gpg` encrypted file to store your Ansible vault password, you can set the vault password by declaring the `ANSIBLE_VAULT_PASSWORD` environment variable as follow:

```
$ export ANSIBLE_VAULT_PASSWORD="supersecret"
```

If you plan to use a GPG encrypted file instead (which we recommend), you must create a `.teams` file with all emails attached to GPG keys of your collaborators listed, and then generate a random password encrypted file _via_:

```bash
# Create a .team file with all collaborators
$ echo -e "foo@example.org\nbar@example.com" > .team
# Create a random encrypted password file for the development/hd-inc project
$ bin/arnold -c hd-inc -e development vault_pw
```

HTH.

**Comment by moticanvm** [comment]
Thank you vey much. That worked. However, I run in the next issue right after that I posted here #720 

Any insights would be appreciated!
