### ISSUE TITLE
Prune old OpenShift resources

### ISSUE THREAD

**Issue by cchaudier** [openfun/arnold#73]
## Purpose

OpenShift ressources (builds, deployements, pods, jobs) must be purged.
We can do it automatically with some configurations on templates.

## Proposal

- [ ] add auto-prune on all OpenShift objects.

**Comment by sampaccoud** [comment]
Could be a subject for @rouja and I on July 16th.

**Comment by jmaupetit** [comment]
Closing as duplicate of #135
