### ISSUE TITLE
add apps.services.*.host on auto-discovery apps method

### ISSUE THREAD

**Issue by cchaudier** [openfun/arnold#74]
## Purpose

Currently, the creation of static routes is generic and based on the presence of host variables in a service.
If we use the directory apps auto-discovery method, we do not have this host variable on dict.

## Proposal
On app default var file (main.yml) create list whit the services who need's route.
The generic patern of the routes is : `(previous|current|next).{{ app.service.name }}.{{ project_name }}.{{ domain_name }}`

**Comment by jmaupetit** [comment]
We choose to remove the generic template for routes in favor to a declarative route template for each application service.
