### ISSUE TITLE
Openshift

### ISSUE THREAD

**Issue by jo316it** [openfun/arnold#785]
I  have a task where I need to make Open edX work via Kubernetes. Through recommendations, I arrived at this repository. I tried to install it, but I reached a point where it complains that it couldn't find OpenShift. I'm doing this installation on GKE to later take it to an on-premises environment. My question is, should I have OpenShift installed on the server?

I don't got it find in the closed questions about it.

Enviroment: Cluster GKE and Linux Ubuntu
![openerror](https://github.com/openfun/arnold/assets/119107380/b2e2ea4d-1f5a-4fab-9558-f49592fa1b7a)

**Comment by lunika** [comment]
Hello,

What version of Arnold are you using ? Arnold is working with k8s since version 6.0.0 and you should use the last available version.

**Comment by jo316it** [comment]
Hi Lunika,

I've been using the version  6.19.1.

Regards

**Comment by lunika** [comment]
I don't find this task `Make sute the project exists in OpenShift and is up-to-date`. What command are you running ?

**Comment by lunika** [comment]
Do you have this log at the beginning `Consider upgrading Arnold using the 'upgrade' command` ? If yes can you run `./bin/arnold upgrade` ?

**Comment by jo316it** [comment]
About the command is "arnold bootstrap -c hd-inc -e development -a hello". I'm doing just a test to learn about it

![image](https://github.com/openfun/arnold/assets/119107380/f533eb91-387b-48b5-abbf-c75b4b677c27)
![image](https://github.com/openfun/arnold/assets/119107380/c0120dac-befb-44e5-ae37-fc0d5f932852)

About the log, as in the image, I didn't upgrade it yet, I'm gonna do it now and I post here what happened. 

Regards

**Comment by jo316it** [comment]
Hi,
After upgrad it works!
Thank you!
